// source: ServerMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ServerMessage', null, global);
goog.exportSymbol('proto.ServerMessage.EntityData', null, global);
goog.exportSymbol('proto.ServerMessage.EntityDestroyed', null, global);
goog.exportSymbol('proto.ServerMessage.MsgdataCase', null, global);
goog.exportSymbol('proto.ServerMessage.Snapshot', null, global);
goog.exportSymbol('proto.ServerMessage.UpdateTick', null, global);
goog.exportSymbol('proto.ServerMessage.VerifiedUuid', null, global);
goog.exportSymbol('proto.ServerMessage.VerifyUuid', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ServerMessage.oneofGroups_);
};
goog.inherits(proto.ServerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.displayName = 'proto.ServerMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.UpdateTick = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerMessage.UpdateTick, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.UpdateTick.displayName = 'proto.ServerMessage.UpdateTick';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.VerifyUuid = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerMessage.VerifyUuid, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.VerifyUuid.displayName = 'proto.ServerMessage.VerifyUuid';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.VerifiedUuid = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerMessage.VerifiedUuid, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.VerifiedUuid.displayName = 'proto.ServerMessage.VerifiedUuid';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.EntityDestroyed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerMessage.EntityDestroyed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.EntityDestroyed.displayName = 'proto.ServerMessage.EntityDestroyed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.Snapshot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ServerMessage.Snapshot.repeatedFields_, null);
};
goog.inherits(proto.ServerMessage.Snapshot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.Snapshot.displayName = 'proto.ServerMessage.Snapshot';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage.EntityData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ServerMessage.EntityData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ServerMessage.EntityData.displayName = 'proto.ServerMessage.EntityData';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ServerMessage.oneofGroups_ = [[1,2,5,25,26]];

/**
 * @enum {number}
 */
proto.ServerMessage.MsgdataCase = {
  MSGDATA_NOT_SET: 0,
  UPDATETICK: 1,
  SNAPSHOT: 2,
  ENTITYDESTROYED: 5,
  VERIFYUUID: 25,
  VERIFIEDUUID: 26
};

/**
 * @return {proto.ServerMessage.MsgdataCase}
 */
proto.ServerMessage.prototype.getMsgdataCase = function() {
  return /** @type {proto.ServerMessage.MsgdataCase} */(jspb.Message.computeOneofCase(this, proto.ServerMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    updatetick: (f = msg.getUpdatetick()) && proto.ServerMessage.UpdateTick.toObject(includeInstance, f),
    snapshot: (f = msg.getSnapshot()) && proto.ServerMessage.Snapshot.toObject(includeInstance, f),
    entitydestroyed: (f = msg.getEntitydestroyed()) && proto.ServerMessage.EntityDestroyed.toObject(includeInstance, f),
    verifyuuid: (f = msg.getVerifyuuid()) && proto.ServerMessage.VerifyUuid.toObject(includeInstance, f),
    verifieduuid: (f = msg.getVerifieduuid()) && proto.ServerMessage.VerifiedUuid.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage}
 */
proto.ServerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage;
  return proto.ServerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage}
 */
proto.ServerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ServerMessage.UpdateTick;
      reader.readMessage(value,proto.ServerMessage.UpdateTick.deserializeBinaryFromReader);
      msg.setUpdatetick(value);
      break;
    case 2:
      var value = new proto.ServerMessage.Snapshot;
      reader.readMessage(value,proto.ServerMessage.Snapshot.deserializeBinaryFromReader);
      msg.setSnapshot(value);
      break;
    case 5:
      var value = new proto.ServerMessage.EntityDestroyed;
      reader.readMessage(value,proto.ServerMessage.EntityDestroyed.deserializeBinaryFromReader);
      msg.setEntitydestroyed(value);
      break;
    case 25:
      var value = new proto.ServerMessage.VerifyUuid;
      reader.readMessage(value,proto.ServerMessage.VerifyUuid.deserializeBinaryFromReader);
      msg.setVerifyuuid(value);
      break;
    case 26:
      var value = new proto.ServerMessage.VerifiedUuid;
      reader.readMessage(value,proto.ServerMessage.VerifiedUuid.deserializeBinaryFromReader);
      msg.setVerifieduuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdatetick();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ServerMessage.UpdateTick.serializeBinaryToWriter
    );
  }
  f = message.getSnapshot();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ServerMessage.Snapshot.serializeBinaryToWriter
    );
  }
  f = message.getEntitydestroyed();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.ServerMessage.EntityDestroyed.serializeBinaryToWriter
    );
  }
  f = message.getVerifyuuid();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto.ServerMessage.VerifyUuid.serializeBinaryToWriter
    );
  }
  f = message.getVerifieduuid();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto.ServerMessage.VerifiedUuid.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.UpdateTick.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.UpdateTick.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.UpdateTick} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.UpdateTick.toObject = function(includeInstance, msg) {
  var f, obj = {
    frame: jspb.Message.getFieldWithDefault(msg, 1, 0),
    replicationid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.UpdateTick}
 */
proto.ServerMessage.UpdateTick.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.UpdateTick;
  return proto.ServerMessage.UpdateTick.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.UpdateTick} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.UpdateTick}
 */
proto.ServerMessage.UpdateTick.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFrame(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReplicationid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.UpdateTick.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.UpdateTick.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.UpdateTick} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.UpdateTick.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrame();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getReplicationid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional uint32 frame = 1;
 * @return {number}
 */
proto.ServerMessage.UpdateTick.prototype.getFrame = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.UpdateTick} returns this
 */
proto.ServerMessage.UpdateTick.prototype.setFrame = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 replicationId = 2;
 * @return {number}
 */
proto.ServerMessage.UpdateTick.prototype.getReplicationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.UpdateTick} returns this
 */
proto.ServerMessage.UpdateTick.prototype.setReplicationid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float x = 3;
 * @return {number}
 */
proto.ServerMessage.UpdateTick.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.UpdateTick} returns this
 */
proto.ServerMessage.UpdateTick.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float y = 4;
 * @return {number}
 */
proto.ServerMessage.UpdateTick.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.UpdateTick} returns this
 */
proto.ServerMessage.UpdateTick.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.VerifyUuid.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.VerifyUuid.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.VerifyUuid} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.VerifyUuid.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.VerifyUuid}
 */
proto.ServerMessage.VerifyUuid.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.VerifyUuid;
  return proto.ServerMessage.VerifyUuid.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.VerifyUuid} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.VerifyUuid}
 */
proto.ServerMessage.VerifyUuid.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.VerifyUuid.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.VerifyUuid.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.VerifyUuid} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.VerifyUuid.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.ServerMessage.VerifyUuid.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ServerMessage.VerifyUuid} returns this
 */
proto.ServerMessage.VerifyUuid.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.VerifiedUuid.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.VerifiedUuid.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.VerifiedUuid} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.VerifiedUuid.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.VerifiedUuid}
 */
proto.ServerMessage.VerifiedUuid.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.VerifiedUuid;
  return proto.ServerMessage.VerifiedUuid.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.VerifiedUuid} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.VerifiedUuid}
 */
proto.ServerMessage.VerifiedUuid.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.VerifiedUuid.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.VerifiedUuid.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.VerifiedUuid} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.VerifiedUuid.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.EntityDestroyed.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.EntityDestroyed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.EntityDestroyed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.EntityDestroyed.toObject = function(includeInstance, msg) {
  var f, obj = {
    frame: jspb.Message.getFieldWithDefault(msg, 1, 0),
    replicationid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.EntityDestroyed}
 */
proto.ServerMessage.EntityDestroyed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.EntityDestroyed;
  return proto.ServerMessage.EntityDestroyed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.EntityDestroyed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.EntityDestroyed}
 */
proto.ServerMessage.EntityDestroyed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFrame(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReplicationid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.EntityDestroyed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.EntityDestroyed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.EntityDestroyed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.EntityDestroyed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrame();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getReplicationid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 frame = 1;
 * @return {number}
 */
proto.ServerMessage.EntityDestroyed.prototype.getFrame = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.EntityDestroyed} returns this
 */
proto.ServerMessage.EntityDestroyed.prototype.setFrame = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 replicationId = 2;
 * @return {number}
 */
proto.ServerMessage.EntityDestroyed.prototype.getReplicationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.EntityDestroyed} returns this
 */
proto.ServerMessage.EntityDestroyed.prototype.setReplicationid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ServerMessage.Snapshot.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.Snapshot.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.Snapshot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.Snapshot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.Snapshot.toObject = function(includeInstance, msg) {
  var f, obj = {
    frame: jspb.Message.getFieldWithDefault(msg, 1, 0),
    entitydataList: jspb.Message.toObjectList(msg.getEntitydataList(),
    proto.ServerMessage.EntityData.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.Snapshot}
 */
proto.ServerMessage.Snapshot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.Snapshot;
  return proto.ServerMessage.Snapshot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.Snapshot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.Snapshot}
 */
proto.ServerMessage.Snapshot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFrame(value);
      break;
    case 2:
      var value = new proto.ServerMessage.EntityData;
      reader.readMessage(value,proto.ServerMessage.EntityData.deserializeBinaryFromReader);
      msg.addEntitydata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.Snapshot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.Snapshot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.Snapshot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.Snapshot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrame();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getEntitydataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ServerMessage.EntityData.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 frame = 1;
 * @return {number}
 */
proto.ServerMessage.Snapshot.prototype.getFrame = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.Snapshot} returns this
 */
proto.ServerMessage.Snapshot.prototype.setFrame = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated EntityData entityData = 2;
 * @return {!Array<!proto.ServerMessage.EntityData>}
 */
proto.ServerMessage.Snapshot.prototype.getEntitydataList = function() {
  return /** @type{!Array<!proto.ServerMessage.EntityData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ServerMessage.EntityData, 2));
};


/**
 * @param {!Array<!proto.ServerMessage.EntityData>} value
 * @return {!proto.ServerMessage.Snapshot} returns this
*/
proto.ServerMessage.Snapshot.prototype.setEntitydataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ServerMessage.EntityData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ServerMessage.EntityData}
 */
proto.ServerMessage.Snapshot.prototype.addEntitydata = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ServerMessage.EntityData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ServerMessage.Snapshot} returns this
 */
proto.ServerMessage.Snapshot.prototype.clearEntitydataList = function() {
  return this.setEntitydataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.EntityData.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.EntityData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage.EntityData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.EntityData.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    replicationid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage.EntityData}
 */
proto.ServerMessage.EntityData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage.EntityData;
  return proto.ServerMessage.EntityData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage.EntityData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage.EntityData}
 */
proto.ServerMessage.EntityData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReplicationid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.EntityData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.EntityData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage.EntityData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.EntityData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getReplicationid();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.ServerMessage.EntityData.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.EntityData} returns this
 */
proto.ServerMessage.EntityData.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.ServerMessage.EntityData.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.EntityData} returns this
 */
proto.ServerMessage.EntityData.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional uint32 replicationId = 3;
 * @return {number}
 */
proto.ServerMessage.EntityData.prototype.getReplicationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ServerMessage.EntityData} returns this
 */
proto.ServerMessage.EntityData.prototype.setReplicationid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional UpdateTick updateTick = 1;
 * @return {?proto.ServerMessage.UpdateTick}
 */
proto.ServerMessage.prototype.getUpdatetick = function() {
  return /** @type{?proto.ServerMessage.UpdateTick} */ (
    jspb.Message.getWrapperField(this, proto.ServerMessage.UpdateTick, 1));
};


/**
 * @param {?proto.ServerMessage.UpdateTick|undefined} value
 * @return {!proto.ServerMessage} returns this
*/
proto.ServerMessage.prototype.setUpdatetick = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerMessage} returns this
 */
proto.ServerMessage.prototype.clearUpdatetick = function() {
  return this.setUpdatetick(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerMessage.prototype.hasUpdatetick = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Snapshot snapshot = 2;
 * @return {?proto.ServerMessage.Snapshot}
 */
proto.ServerMessage.prototype.getSnapshot = function() {
  return /** @type{?proto.ServerMessage.Snapshot} */ (
    jspb.Message.getWrapperField(this, proto.ServerMessage.Snapshot, 2));
};


/**
 * @param {?proto.ServerMessage.Snapshot|undefined} value
 * @return {!proto.ServerMessage} returns this
*/
proto.ServerMessage.prototype.setSnapshot = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerMessage} returns this
 */
proto.ServerMessage.prototype.clearSnapshot = function() {
  return this.setSnapshot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerMessage.prototype.hasSnapshot = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EntityDestroyed entityDestroyed = 5;
 * @return {?proto.ServerMessage.EntityDestroyed}
 */
proto.ServerMessage.prototype.getEntitydestroyed = function() {
  return /** @type{?proto.ServerMessage.EntityDestroyed} */ (
    jspb.Message.getWrapperField(this, proto.ServerMessage.EntityDestroyed, 5));
};


/**
 * @param {?proto.ServerMessage.EntityDestroyed|undefined} value
 * @return {!proto.ServerMessage} returns this
*/
proto.ServerMessage.prototype.setEntitydestroyed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerMessage} returns this
 */
proto.ServerMessage.prototype.clearEntitydestroyed = function() {
  return this.setEntitydestroyed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerMessage.prototype.hasEntitydestroyed = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional VerifyUuid verifyUuid = 25;
 * @return {?proto.ServerMessage.VerifyUuid}
 */
proto.ServerMessage.prototype.getVerifyuuid = function() {
  return /** @type{?proto.ServerMessage.VerifyUuid} */ (
    jspb.Message.getWrapperField(this, proto.ServerMessage.VerifyUuid, 25));
};


/**
 * @param {?proto.ServerMessage.VerifyUuid|undefined} value
 * @return {!proto.ServerMessage} returns this
*/
proto.ServerMessage.prototype.setVerifyuuid = function(value) {
  return jspb.Message.setOneofWrapperField(this, 25, proto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerMessage} returns this
 */
proto.ServerMessage.prototype.clearVerifyuuid = function() {
  return this.setVerifyuuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerMessage.prototype.hasVerifyuuid = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional VerifiedUuid verifiedUuid = 26;
 * @return {?proto.ServerMessage.VerifiedUuid}
 */
proto.ServerMessage.prototype.getVerifieduuid = function() {
  return /** @type{?proto.ServerMessage.VerifiedUuid} */ (
    jspb.Message.getWrapperField(this, proto.ServerMessage.VerifiedUuid, 26));
};


/**
 * @param {?proto.ServerMessage.VerifiedUuid|undefined} value
 * @return {!proto.ServerMessage} returns this
*/
proto.ServerMessage.prototype.setVerifieduuid = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.ServerMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ServerMessage} returns this
 */
proto.ServerMessage.prototype.clearVerifieduuid = function() {
  return this.setVerifieduuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ServerMessage.prototype.hasVerifieduuid = function() {
  return jspb.Message.getField(this, 26) != null;
};


goog.object.extend(exports, proto);
