[package]
name = "moba_server"
version = "0.1.0"
authors = ["Zerve0 <zerve0@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
legion = "0.2.1"
ws = "*"
nalgebra = "0.18"
ncollide2d = "0.20"
nphysics2d = "0.12"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"