// This file is generated by rust-protobuf 2.10.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `ServerMessage.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_10_1;

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage {
    // message oneof groups
    pub msgData: ::std::option::Option<ServerMessage_oneof_msgData>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage {
    fn default() -> &'a ServerMessage {
        <ServerMessage as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum ServerMessage_oneof_msgData {
    updateTick(ServerMessage_UpdateTick),
    snapshot(ServerMessage_Snapshot),
    entityDestroyed(ServerMessage_EntityDestroyed),
    verifyUuid(ServerMessage_VerifyUuid),
    verifiedUuid(ServerMessage_VerifiedUuid),
}

impl ServerMessage {
    pub fn new() -> ServerMessage {
        ::std::default::Default::default()
    }

    // .ServerMessage.UpdateTick updateTick = 1;


    pub fn get_updateTick(&self) -> &ServerMessage_UpdateTick {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(ref v)) => v,
            _ => ServerMessage_UpdateTick::default_instance(),
        }
    }
    pub fn clear_updateTick(&mut self) {
        self.msgData = ::std::option::Option::None;
    }

    pub fn has_updateTick(&self) -> bool {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_updateTick(&mut self, v: ServerMessage_UpdateTick) {
        self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(v))
    }

    // Mutable pointer to the field.
    pub fn mut_updateTick(&mut self) -> &mut ServerMessage_UpdateTick {
        if let ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(_)) = self.msgData {
        } else {
            self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(ServerMessage_UpdateTick::new()));
        }
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_updateTick(&mut self) -> ServerMessage_UpdateTick {
        if self.has_updateTick() {
            match self.msgData.take() {
                ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(v)) => v,
                _ => panic!(),
            }
        } else {
            ServerMessage_UpdateTick::new()
        }
    }

    // .ServerMessage.Snapshot snapshot = 2;


    pub fn get_snapshot(&self) -> &ServerMessage_Snapshot {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(ref v)) => v,
            _ => ServerMessage_Snapshot::default_instance(),
        }
    }
    pub fn clear_snapshot(&mut self) {
        self.msgData = ::std::option::Option::None;
    }

    pub fn has_snapshot(&self) -> bool {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_snapshot(&mut self, v: ServerMessage_Snapshot) {
        self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(v))
    }

    // Mutable pointer to the field.
    pub fn mut_snapshot(&mut self) -> &mut ServerMessage_Snapshot {
        if let ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(_)) = self.msgData {
        } else {
            self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(ServerMessage_Snapshot::new()));
        }
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_snapshot(&mut self) -> ServerMessage_Snapshot {
        if self.has_snapshot() {
            match self.msgData.take() {
                ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(v)) => v,
                _ => panic!(),
            }
        } else {
            ServerMessage_Snapshot::new()
        }
    }

    // .ServerMessage.EntityDestroyed entityDestroyed = 5;


    pub fn get_entityDestroyed(&self) -> &ServerMessage_EntityDestroyed {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(ref v)) => v,
            _ => ServerMessage_EntityDestroyed::default_instance(),
        }
    }
    pub fn clear_entityDestroyed(&mut self) {
        self.msgData = ::std::option::Option::None;
    }

    pub fn has_entityDestroyed(&self) -> bool {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_entityDestroyed(&mut self, v: ServerMessage_EntityDestroyed) {
        self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(v))
    }

    // Mutable pointer to the field.
    pub fn mut_entityDestroyed(&mut self) -> &mut ServerMessage_EntityDestroyed {
        if let ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(_)) = self.msgData {
        } else {
            self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(ServerMessage_EntityDestroyed::new()));
        }
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_entityDestroyed(&mut self) -> ServerMessage_EntityDestroyed {
        if self.has_entityDestroyed() {
            match self.msgData.take() {
                ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(v)) => v,
                _ => panic!(),
            }
        } else {
            ServerMessage_EntityDestroyed::new()
        }
    }

    // .ServerMessage.VerifyUuid verifyUuid = 25;


    pub fn get_verifyUuid(&self) -> &ServerMessage_VerifyUuid {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(ref v)) => v,
            _ => ServerMessage_VerifyUuid::default_instance(),
        }
    }
    pub fn clear_verifyUuid(&mut self) {
        self.msgData = ::std::option::Option::None;
    }

    pub fn has_verifyUuid(&self) -> bool {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_verifyUuid(&mut self, v: ServerMessage_VerifyUuid) {
        self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(v))
    }

    // Mutable pointer to the field.
    pub fn mut_verifyUuid(&mut self) -> &mut ServerMessage_VerifyUuid {
        if let ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(_)) = self.msgData {
        } else {
            self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(ServerMessage_VerifyUuid::new()));
        }
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_verifyUuid(&mut self) -> ServerMessage_VerifyUuid {
        if self.has_verifyUuid() {
            match self.msgData.take() {
                ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(v)) => v,
                _ => panic!(),
            }
        } else {
            ServerMessage_VerifyUuid::new()
        }
    }

    // .ServerMessage.VerifiedUuid verifiedUuid = 26;


    pub fn get_verifiedUuid(&self) -> &ServerMessage_VerifiedUuid {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(ref v)) => v,
            _ => ServerMessage_VerifiedUuid::default_instance(),
        }
    }
    pub fn clear_verifiedUuid(&mut self) {
        self.msgData = ::std::option::Option::None;
    }

    pub fn has_verifiedUuid(&self) -> bool {
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_verifiedUuid(&mut self, v: ServerMessage_VerifiedUuid) {
        self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(v))
    }

    // Mutable pointer to the field.
    pub fn mut_verifiedUuid(&mut self) -> &mut ServerMessage_VerifiedUuid {
        if let ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(_)) = self.msgData {
        } else {
            self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(ServerMessage_VerifiedUuid::new()));
        }
        match self.msgData {
            ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_verifiedUuid(&mut self) -> ServerMessage_VerifiedUuid {
        if self.has_verifiedUuid() {
            match self.msgData.take() {
                ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(v)) => v,
                _ => panic!(),
            }
        } else {
            ServerMessage_VerifiedUuid::new()
        }
    }
}

impl ::protobuf::Message for ServerMessage {
    fn is_initialized(&self) -> bool {
        if let Some(ServerMessage_oneof_msgData::updateTick(ref v)) = self.msgData {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ServerMessage_oneof_msgData::snapshot(ref v)) = self.msgData {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ServerMessage_oneof_msgData::entityDestroyed(ref v)) = self.msgData {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ServerMessage_oneof_msgData::verifyUuid(ref v)) = self.msgData {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(ServerMessage_oneof_msgData::verifiedUuid(ref v)) = self.msgData {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::updateTick(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::snapshot(is.read_message()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::entityDestroyed(is.read_message()?));
                },
                25 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifyUuid(is.read_message()?));
                },
                26 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.msgData = ::std::option::Option::Some(ServerMessage_oneof_msgData::verifiedUuid(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.msgData {
            match v {
                &ServerMessage_oneof_msgData::updateTick(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ServerMessage_oneof_msgData::snapshot(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ServerMessage_oneof_msgData::entityDestroyed(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ServerMessage_oneof_msgData::verifyUuid(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &ServerMessage_oneof_msgData::verifiedUuid(ref v) => {
                    let len = v.compute_size();
                    my_size += 2 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.msgData {
            match v {
                &ServerMessage_oneof_msgData::updateTick(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ServerMessage_oneof_msgData::snapshot(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ServerMessage_oneof_msgData::entityDestroyed(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ServerMessage_oneof_msgData::verifyUuid(ref v) => {
                    os.write_tag(25, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &ServerMessage_oneof_msgData::verifiedUuid(ref v) => {
                    os.write_tag(26, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage {
        ServerMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ServerMessage_UpdateTick>(
                    "updateTick",
                    ServerMessage::has_updateTick,
                    ServerMessage::get_updateTick,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ServerMessage_Snapshot>(
                    "snapshot",
                    ServerMessage::has_snapshot,
                    ServerMessage::get_snapshot,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ServerMessage_EntityDestroyed>(
                    "entityDestroyed",
                    ServerMessage::has_entityDestroyed,
                    ServerMessage::get_entityDestroyed,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ServerMessage_VerifyUuid>(
                    "verifyUuid",
                    ServerMessage::has_verifyUuid,
                    ServerMessage::get_verifyUuid,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, ServerMessage_VerifiedUuid>(
                    "verifiedUuid",
                    ServerMessage::has_verifiedUuid,
                    ServerMessage::get_verifiedUuid,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage>(
                    "ServerMessage",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage,
        };
        unsafe {
            instance.get(ServerMessage::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage {
    fn clear(&mut self) {
        self.msgData = ::std::option::Option::None;
        self.msgData = ::std::option::Option::None;
        self.msgData = ::std::option::Option::None;
        self.msgData = ::std::option::Option::None;
        self.msgData = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_UpdateTick {
    // message fields
    pub frame: u32,
    pub entityData: ::protobuf::SingularPtrField<ServerMessage_EntityData>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_UpdateTick {
    fn default() -> &'a ServerMessage_UpdateTick {
        <ServerMessage_UpdateTick as ::protobuf::Message>::default_instance()
    }
}

impl ServerMessage_UpdateTick {
    pub fn new() -> ServerMessage_UpdateTick {
        ::std::default::Default::default()
    }

    // uint32 frame = 1;


    pub fn get_frame(&self) -> u32 {
        self.frame
    }
    pub fn clear_frame(&mut self) {
        self.frame = 0;
    }

    // Param is passed by value, moved
    pub fn set_frame(&mut self, v: u32) {
        self.frame = v;
    }

    // .ServerMessage.EntityData entityData = 2;


    pub fn get_entityData(&self) -> &ServerMessage_EntityData {
        self.entityData.as_ref().unwrap_or_else(|| ServerMessage_EntityData::default_instance())
    }
    pub fn clear_entityData(&mut self) {
        self.entityData.clear();
    }

    pub fn has_entityData(&self) -> bool {
        self.entityData.is_some()
    }

    // Param is passed by value, moved
    pub fn set_entityData(&mut self, v: ServerMessage_EntityData) {
        self.entityData = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_entityData(&mut self) -> &mut ServerMessage_EntityData {
        if self.entityData.is_none() {
            self.entityData.set_default();
        }
        self.entityData.as_mut().unwrap()
    }

    // Take field
    pub fn take_entityData(&mut self) -> ServerMessage_EntityData {
        self.entityData.take().unwrap_or_else(|| ServerMessage_EntityData::new())
    }
}

impl ::protobuf::Message for ServerMessage_UpdateTick {
    fn is_initialized(&self) -> bool {
        for v in &self.entityData {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.frame = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.entityData)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.frame != 0 {
            my_size += ::protobuf::rt::value_size(1, self.frame, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.entityData.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.frame != 0 {
            os.write_uint32(1, self.frame)?;
        }
        if let Some(ref v) = self.entityData.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_UpdateTick {
        ServerMessage_UpdateTick::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "frame",
                    |m: &ServerMessage_UpdateTick| { &m.frame },
                    |m: &mut ServerMessage_UpdateTick| { &mut m.frame },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ServerMessage_EntityData>>(
                    "entityData",
                    |m: &ServerMessage_UpdateTick| { &m.entityData },
                    |m: &mut ServerMessage_UpdateTick| { &mut m.entityData },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_UpdateTick>(
                    "ServerMessage_UpdateTick",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_UpdateTick {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_UpdateTick> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_UpdateTick,
        };
        unsafe {
            instance.get(ServerMessage_UpdateTick::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_UpdateTick {
    fn clear(&mut self) {
        self.frame = 0;
        self.entityData.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_UpdateTick {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_UpdateTick {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_VerifyUuid {
    // message fields
    pub uuid: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_VerifyUuid {
    fn default() -> &'a ServerMessage_VerifyUuid {
        <ServerMessage_VerifyUuid as ::protobuf::Message>::default_instance()
    }
}

impl ServerMessage_VerifyUuid {
    pub fn new() -> ServerMessage_VerifyUuid {
        ::std::default::Default::default()
    }

    // string uuid = 1;


    pub fn get_uuid(&self) -> &str {
        &self.uuid
    }
    pub fn clear_uuid(&mut self) {
        self.uuid.clear();
    }

    // Param is passed by value, moved
    pub fn set_uuid(&mut self, v: ::std::string::String) {
        self.uuid = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_uuid(&mut self) -> &mut ::std::string::String {
        &mut self.uuid
    }

    // Take field
    pub fn take_uuid(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.uuid, ::std::string::String::new())
    }
}

impl ::protobuf::Message for ServerMessage_VerifyUuid {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.uuid)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.uuid.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.uuid);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.uuid.is_empty() {
            os.write_string(1, &self.uuid)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_VerifyUuid {
        ServerMessage_VerifyUuid::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "uuid",
                    |m: &ServerMessage_VerifyUuid| { &m.uuid },
                    |m: &mut ServerMessage_VerifyUuid| { &mut m.uuid },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_VerifyUuid>(
                    "ServerMessage_VerifyUuid",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_VerifyUuid {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_VerifyUuid> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_VerifyUuid,
        };
        unsafe {
            instance.get(ServerMessage_VerifyUuid::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_VerifyUuid {
    fn clear(&mut self) {
        self.uuid.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_VerifyUuid {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_VerifyUuid {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_VerifiedUuid {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_VerifiedUuid {
    fn default() -> &'a ServerMessage_VerifiedUuid {
        <ServerMessage_VerifiedUuid as ::protobuf::Message>::default_instance()
    }
}

impl ServerMessage_VerifiedUuid {
    pub fn new() -> ServerMessage_VerifiedUuid {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for ServerMessage_VerifiedUuid {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_VerifiedUuid {
        ServerMessage_VerifiedUuid::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_VerifiedUuid>(
                    "ServerMessage_VerifiedUuid",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_VerifiedUuid {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_VerifiedUuid> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_VerifiedUuid,
        };
        unsafe {
            instance.get(ServerMessage_VerifiedUuid::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_VerifiedUuid {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_VerifiedUuid {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_VerifiedUuid {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_EntityDestroyed {
    // message fields
    pub frame: u32,
    pub replicationId: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_EntityDestroyed {
    fn default() -> &'a ServerMessage_EntityDestroyed {
        <ServerMessage_EntityDestroyed as ::protobuf::Message>::default_instance()
    }
}

impl ServerMessage_EntityDestroyed {
    pub fn new() -> ServerMessage_EntityDestroyed {
        ::std::default::Default::default()
    }

    // uint32 frame = 1;


    pub fn get_frame(&self) -> u32 {
        self.frame
    }
    pub fn clear_frame(&mut self) {
        self.frame = 0;
    }

    // Param is passed by value, moved
    pub fn set_frame(&mut self, v: u32) {
        self.frame = v;
    }

    // uint32 replicationId = 2;


    pub fn get_replicationId(&self) -> u32 {
        self.replicationId
    }
    pub fn clear_replicationId(&mut self) {
        self.replicationId = 0;
    }

    // Param is passed by value, moved
    pub fn set_replicationId(&mut self, v: u32) {
        self.replicationId = v;
    }
}

impl ::protobuf::Message for ServerMessage_EntityDestroyed {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.frame = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.replicationId = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.frame != 0 {
            my_size += ::protobuf::rt::value_size(1, self.frame, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.replicationId != 0 {
            my_size += ::protobuf::rt::value_size(2, self.replicationId, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.frame != 0 {
            os.write_uint32(1, self.frame)?;
        }
        if self.replicationId != 0 {
            os.write_uint32(2, self.replicationId)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_EntityDestroyed {
        ServerMessage_EntityDestroyed::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "frame",
                    |m: &ServerMessage_EntityDestroyed| { &m.frame },
                    |m: &mut ServerMessage_EntityDestroyed| { &mut m.frame },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "replicationId",
                    |m: &ServerMessage_EntityDestroyed| { &m.replicationId },
                    |m: &mut ServerMessage_EntityDestroyed| { &mut m.replicationId },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_EntityDestroyed>(
                    "ServerMessage_EntityDestroyed",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_EntityDestroyed {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_EntityDestroyed> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_EntityDestroyed,
        };
        unsafe {
            instance.get(ServerMessage_EntityDestroyed::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_EntityDestroyed {
    fn clear(&mut self) {
        self.frame = 0;
        self.replicationId = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_EntityDestroyed {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_EntityDestroyed {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_Snapshot {
    // message fields
    pub frame: u32,
    pub entityData: ::protobuf::RepeatedField<ServerMessage_EntityData>,
    // message oneof groups
    pub option_baseline: ::std::option::Option<ServerMessage_Snapshot_oneof_option_baseline>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_Snapshot {
    fn default() -> &'a ServerMessage_Snapshot {
        <ServerMessage_Snapshot as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum ServerMessage_Snapshot_oneof_option_baseline {
    baseline(u32),
}

impl ServerMessage_Snapshot {
    pub fn new() -> ServerMessage_Snapshot {
        ::std::default::Default::default()
    }

    // uint32 frame = 1;


    pub fn get_frame(&self) -> u32 {
        self.frame
    }
    pub fn clear_frame(&mut self) {
        self.frame = 0;
    }

    // Param is passed by value, moved
    pub fn set_frame(&mut self, v: u32) {
        self.frame = v;
    }

    // uint32 baseline = 2;


    pub fn get_baseline(&self) -> u32 {
        match self.option_baseline {
            ::std::option::Option::Some(ServerMessage_Snapshot_oneof_option_baseline::baseline(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_baseline(&mut self) {
        self.option_baseline = ::std::option::Option::None;
    }

    pub fn has_baseline(&self) -> bool {
        match self.option_baseline {
            ::std::option::Option::Some(ServerMessage_Snapshot_oneof_option_baseline::baseline(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_baseline(&mut self, v: u32) {
        self.option_baseline = ::std::option::Option::Some(ServerMessage_Snapshot_oneof_option_baseline::baseline(v))
    }

    // repeated .ServerMessage.EntityData entityData = 3;


    pub fn get_entityData(&self) -> &[ServerMessage_EntityData] {
        &self.entityData
    }
    pub fn clear_entityData(&mut self) {
        self.entityData.clear();
    }

    // Param is passed by value, moved
    pub fn set_entityData(&mut self, v: ::protobuf::RepeatedField<ServerMessage_EntityData>) {
        self.entityData = v;
    }

    // Mutable pointer to the field.
    pub fn mut_entityData(&mut self) -> &mut ::protobuf::RepeatedField<ServerMessage_EntityData> {
        &mut self.entityData
    }

    // Take field
    pub fn take_entityData(&mut self) -> ::protobuf::RepeatedField<ServerMessage_EntityData> {
        ::std::mem::replace(&mut self.entityData, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ServerMessage_Snapshot {
    fn is_initialized(&self) -> bool {
        for v in &self.entityData {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.frame = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.option_baseline = ::std::option::Option::Some(ServerMessage_Snapshot_oneof_option_baseline::baseline(is.read_uint32()?));
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.entityData)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.frame != 0 {
            my_size += ::protobuf::rt::value_size(1, self.frame, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.entityData {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if let ::std::option::Option::Some(ref v) = self.option_baseline {
            match v {
                &ServerMessage_Snapshot_oneof_option_baseline::baseline(v) => {
                    my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.frame != 0 {
            os.write_uint32(1, self.frame)?;
        }
        for v in &self.entityData {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if let ::std::option::Option::Some(ref v) = self.option_baseline {
            match v {
                &ServerMessage_Snapshot_oneof_option_baseline::baseline(v) => {
                    os.write_uint32(2, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_Snapshot {
        ServerMessage_Snapshot::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "frame",
                    |m: &ServerMessage_Snapshot| { &m.frame },
                    |m: &mut ServerMessage_Snapshot| { &mut m.frame },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_u32_accessor::<_>(
                    "baseline",
                    ServerMessage_Snapshot::has_baseline,
                    ServerMessage_Snapshot::get_baseline,
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ServerMessage_EntityData>>(
                    "entityData",
                    |m: &ServerMessage_Snapshot| { &m.entityData },
                    |m: &mut ServerMessage_Snapshot| { &mut m.entityData },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_Snapshot>(
                    "ServerMessage_Snapshot",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_Snapshot {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_Snapshot> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_Snapshot,
        };
        unsafe {
            instance.get(ServerMessage_Snapshot::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_Snapshot {
    fn clear(&mut self) {
        self.frame = 0;
        self.option_baseline = ::std::option::Option::None;
        self.entityData.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_Snapshot {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_Snapshot {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ServerMessage_EntityData {
    // message fields
    pub replicationId: u32,
    // message oneof groups
    pub option_x: ::std::option::Option<ServerMessage_EntityData_oneof_option_x>,
    pub option_y: ::std::option::Option<ServerMessage_EntityData_oneof_option_y>,
    pub option_rotation: ::std::option::Option<ServerMessage_EntityData_oneof_option_rotation>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ServerMessage_EntityData {
    fn default() -> &'a ServerMessage_EntityData {
        <ServerMessage_EntityData as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum ServerMessage_EntityData_oneof_option_x {
    x(i32),
}

#[derive(Clone,PartialEq,Debug)]
pub enum ServerMessage_EntityData_oneof_option_y {
    y(i32),
}

#[derive(Clone,PartialEq,Debug)]
pub enum ServerMessage_EntityData_oneof_option_rotation {
    rotation(i32),
}

impl ServerMessage_EntityData {
    pub fn new() -> ServerMessage_EntityData {
        ::std::default::Default::default()
    }

    // uint32 replicationId = 1;


    pub fn get_replicationId(&self) -> u32 {
        self.replicationId
    }
    pub fn clear_replicationId(&mut self) {
        self.replicationId = 0;
    }

    // Param is passed by value, moved
    pub fn set_replicationId(&mut self, v: u32) {
        self.replicationId = v;
    }

    // sint32 x = 2;


    pub fn get_x(&self) -> i32 {
        match self.option_x {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_x::x(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_x(&mut self) {
        self.option_x = ::std::option::Option::None;
    }

    pub fn has_x(&self) -> bool {
        match self.option_x {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_x::x(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: i32) {
        self.option_x = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_x::x(v))
    }

    // sint32 y = 3;


    pub fn get_y(&self) -> i32 {
        match self.option_y {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_y::y(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_y(&mut self) {
        self.option_y = ::std::option::Option::None;
    }

    pub fn has_y(&self) -> bool {
        match self.option_y {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_y::y(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: i32) {
        self.option_y = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_y::y(v))
    }

    // sint32 rotation = 4;


    pub fn get_rotation(&self) -> i32 {
        match self.option_rotation {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_rotation::rotation(v)) => v,
            _ => 0,
        }
    }
    pub fn clear_rotation(&mut self) {
        self.option_rotation = ::std::option::Option::None;
    }

    pub fn has_rotation(&self) -> bool {
        match self.option_rotation {
            ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_rotation::rotation(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_rotation(&mut self, v: i32) {
        self.option_rotation = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_rotation::rotation(v))
    }
}

impl ::protobuf::Message for ServerMessage_EntityData {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.replicationId = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.option_x = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_x::x(is.read_sint32()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.option_y = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_y::y(is.read_sint32()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.option_rotation = ::std::option::Option::Some(ServerMessage_EntityData_oneof_option_rotation::rotation(is.read_sint32()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.replicationId != 0 {
            my_size += ::protobuf::rt::value_size(1, self.replicationId, ::protobuf::wire_format::WireTypeVarint);
        }
        if let ::std::option::Option::Some(ref v) = self.option_x {
            match v {
                &ServerMessage_EntityData_oneof_option_x::x(v) => {
                    my_size += ::protobuf::rt::value_varint_zigzag_size(2, v);
                },
            };
        }
        if let ::std::option::Option::Some(ref v) = self.option_y {
            match v {
                &ServerMessage_EntityData_oneof_option_y::y(v) => {
                    my_size += ::protobuf::rt::value_varint_zigzag_size(3, v);
                },
            };
        }
        if let ::std::option::Option::Some(ref v) = self.option_rotation {
            match v {
                &ServerMessage_EntityData_oneof_option_rotation::rotation(v) => {
                    my_size += ::protobuf::rt::value_varint_zigzag_size(4, v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.replicationId != 0 {
            os.write_uint32(1, self.replicationId)?;
        }
        if let ::std::option::Option::Some(ref v) = self.option_x {
            match v {
                &ServerMessage_EntityData_oneof_option_x::x(v) => {
                    os.write_sint32(2, v)?;
                },
            };
        }
        if let ::std::option::Option::Some(ref v) = self.option_y {
            match v {
                &ServerMessage_EntityData_oneof_option_y::y(v) => {
                    os.write_sint32(3, v)?;
                },
            };
        }
        if let ::std::option::Option::Some(ref v) = self.option_rotation {
            match v {
                &ServerMessage_EntityData_oneof_option_rotation::rotation(v) => {
                    os.write_sint32(4, v)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ServerMessage_EntityData {
        ServerMessage_EntityData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "replicationId",
                    |m: &ServerMessage_EntityData| { &m.replicationId },
                    |m: &mut ServerMessage_EntityData| { &mut m.replicationId },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_i32_accessor::<_>(
                    "x",
                    ServerMessage_EntityData::has_x,
                    ServerMessage_EntityData::get_x,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_i32_accessor::<_>(
                    "y",
                    ServerMessage_EntityData::has_y,
                    ServerMessage_EntityData::get_y,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_i32_accessor::<_>(
                    "rotation",
                    ServerMessage_EntityData::has_rotation,
                    ServerMessage_EntityData::get_rotation,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ServerMessage_EntityData>(
                    "ServerMessage_EntityData",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ServerMessage_EntityData {
        static mut instance: ::protobuf::lazy::Lazy<ServerMessage_EntityData> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ServerMessage_EntityData,
        };
        unsafe {
            instance.get(ServerMessage_EntityData::new)
        }
    }
}

impl ::protobuf::Clear for ServerMessage_EntityData {
    fn clear(&mut self) {
        self.replicationId = 0;
        self.option_x = ::std::option::Option::None;
        self.option_y = ::std::option::Option::None;
        self.option_rotation = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ServerMessage_EntityData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerMessage_EntityData {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13ServerMessage.proto\"\xe7\x06\n\rServerMessage\x12;\n\nupdateTick\
    \x18\x01\x20\x01(\x0b2\x19.ServerMessage.UpdateTickH\0R\nupdateTick\x125\
    \n\x08snapshot\x18\x02\x20\x01(\x0b2\x17.ServerMessage.SnapshotH\0R\x08s\
    napshot\x12J\n\x0fentityDestroyed\x18\x05\x20\x01(\x0b2\x1e.ServerMessag\
    e.EntityDestroyedH\0R\x0fentityDestroyed\x12;\n\nverifyUuid\x18\x19\x20\
    \x01(\x0b2\x19.ServerMessage.VerifyUuidH\0R\nverifyUuid\x12A\n\x0cverifi\
    edUuid\x18\x1a\x20\x01(\x0b2\x1b.ServerMessage.VerifiedUuidH\0R\x0cverif\
    iedUuid\x1a]\n\nUpdateTick\x12\x14\n\x05frame\x18\x01\x20\x01(\rR\x05fra\
    me\x129\n\nentityData\x18\x02\x20\x01(\x0b2\x19.ServerMessage.EntityData\
    R\nentityData\x1a\x20\n\nVerifyUuid\x12\x12\n\x04uuid\x18\x01\x20\x01(\t\
    R\x04uuid\x1a\x0e\n\x0cVerifiedUuid\x1aM\n\x0fEntityDestroyed\x12\x14\n\
    \x05frame\x18\x01\x20\x01(\rR\x05frame\x12$\n\rreplicationId\x18\x02\x20\
    \x01(\rR\rreplicationId\x1a\x8c\x01\n\x08Snapshot\x12\x14\n\x05frame\x18\
    \x01\x20\x01(\rR\x05frame\x12\x1c\n\x08baseline\x18\x02\x20\x01(\rH\0R\
    \x08baseline\x129\n\nentityData\x18\x03\x20\x03(\x0b2\x19.ServerMessage.\
    EntityDataR\nentityDataB\x11\n\x0foption_baseline\x1a\x9b\x01\n\nEntityD\
    ata\x12$\n\rreplicationId\x18\x01\x20\x01(\rR\rreplicationId\x12\x0e\n\
    \x01x\x18\x02\x20\x01(\x11H\0R\x01x\x12\x0e\n\x01y\x18\x03\x20\x01(\x11H\
    \x01R\x01y\x12\x1c\n\x08rotation\x18\x04\x20\x01(\x11H\x02R\x08rotationB\
    \n\n\x08option_xB\n\n\x08option_yB\x11\n\x0foption_rotationB\t\n\x07msgD\
    ataJ\x84\x0b\n\x06\x12\x04\0\02\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\n\
    \n\x02\x04\0\x12\x04\x02\02\x01\n\n\n\x03\x04\0\x01\x12\x03\x02\x08\x15\
    \n\x0c\n\x04\x04\0\x03\0\x12\x04\x03\x02\x06\x03\n\x0c\n\x05\x04\0\x03\0\
    \x01\x12\x03\x03\n\x14\n\r\n\x06\x04\0\x03\0\x02\0\x12\x03\x04\x04\x15\n\
    \x0e\n\x07\x04\0\x03\0\x02\0\x05\x12\x03\x04\x04\n\n\x0e\n\x07\x04\0\x03\
    \0\x02\0\x01\x12\x03\x04\x0b\x10\n\x0e\n\x07\x04\0\x03\0\x02\0\x03\x12\
    \x03\x04\x13\x14\n\r\n\x06\x04\0\x03\0\x02\x01\x12\x03\x05\x04\x1e\n\x0e\
    \n\x07\x04\0\x03\0\x02\x01\x06\x12\x03\x05\x04\x0e\n\x0e\n\x07\x04\0\x03\
    \0\x02\x01\x01\x12\x03\x05\x0f\x19\n\x0e\n\x07\x04\0\x03\0\x02\x01\x03\
    \x12\x03\x05\x1c\x1d\n\x0c\n\x04\x04\0\x03\x01\x12\x04\x08\x02\n\x03\n\
    \x0c\n\x05\x04\0\x03\x01\x01\x12\x03\x08\n\x14\n\r\n\x06\x04\0\x03\x01\
    \x02\0\x12\x03\t\x04\x14\n\x0e\n\x07\x04\0\x03\x01\x02\0\x05\x12\x03\t\
    \x04\n\n\x0e\n\x07\x04\0\x03\x01\x02\0\x01\x12\x03\t\x0b\x0f\n\x0e\n\x07\
    \x04\0\x03\x01\x02\0\x03\x12\x03\t\x12\x13\n\x0b\n\x04\x04\0\x03\x02\x12\
    \x03\x0c\x02\x1a\n\x0c\n\x05\x04\0\x03\x02\x01\x12\x03\x0c\n\x16\n\x0c\n\
    \x04\x04\0\x03\x03\x12\x04\x0e\x02\x11\x03\n\x0c\n\x05\x04\0\x03\x03\x01\
    \x12\x03\x0e\n\x19\n\r\n\x06\x04\0\x03\x03\x02\0\x12\x03\x0f\x04\x15\n\
    \x0e\n\x07\x04\0\x03\x03\x02\0\x05\x12\x03\x0f\x04\n\n\x0e\n\x07\x04\0\
    \x03\x03\x02\0\x01\x12\x03\x0f\x0b\x10\n\x0e\n\x07\x04\0\x03\x03\x02\0\
    \x03\x12\x03\x0f\x13\x14\n\r\n\x06\x04\0\x03\x03\x02\x01\x12\x03\x10\x04\
    \x1d\n\x0e\n\x07\x04\0\x03\x03\x02\x01\x05\x12\x03\x10\x04\n\n\x0e\n\x07\
    \x04\0\x03\x03\x02\x01\x01\x12\x03\x10\x0b\x18\n\x0e\n\x07\x04\0\x03\x03\
    \x02\x01\x03\x12\x03\x10\x1b\x1c\n\x0c\n\x04\x04\0\x03\x04\x12\x04\x13\
    \x02\x19\x03\n\x0c\n\x05\x04\0\x03\x04\x01\x12\x03\x13\n\x12\n\r\n\x06\
    \x04\0\x03\x04\x02\0\x12\x03\x14\x04\x15\n\x0e\n\x07\x04\0\x03\x04\x02\0\
    \x05\x12\x03\x14\x04\n\n\x0e\n\x07\x04\0\x03\x04\x02\0\x01\x12\x03\x14\
    \x0b\x10\n\x0e\n\x07\x04\0\x03\x04\x02\0\x03\x12\x03\x14\x13\x14\n\x0e\n\
    \x06\x04\0\x03\x04\x08\0\x12\x04\x15\x04\x17\x05\n\x0e\n\x07\x04\0\x03\
    \x04\x08\0\x01\x12\x03\x15\n\x19\n\r\n\x06\x04\0\x03\x04\x02\x01\x12\x03\
    \x16\x06\x1a\n\x0e\n\x07\x04\0\x03\x04\x02\x01\x05\x12\x03\x16\x06\x0c\n\
    \x0e\n\x07\x04\0\x03\x04\x02\x01\x01\x12\x03\x16\r\x15\n\x0e\n\x07\x04\0\
    \x03\x04\x02\x01\x03\x12\x03\x16\x18\x19\n\r\n\x06\x04\0\x03\x04\x02\x02\
    \x12\x03\x18\x04'\n\x0e\n\x07\x04\0\x03\x04\x02\x02\x04\x12\x03\x18\x04\
    \x0c\n\x0e\n\x07\x04\0\x03\x04\x02\x02\x06\x12\x03\x18\r\x17\n\x0e\n\x07\
    \x04\0\x03\x04\x02\x02\x01\x12\x03\x18\x18\"\n\x0e\n\x07\x04\0\x03\x04\
    \x02\x02\x03\x12\x03\x18%&\n\x0c\n\x04\x04\0\x03\x05\x12\x04\x1b\x02)\
    \x03\n\x0c\n\x05\x04\0\x03\x05\x01\x12\x03\x1b\n\x14\n\r\n\x06\x04\0\x03\
    \x05\x02\0\x12\x03\x1c\x04\x1d\n\x0e\n\x07\x04\0\x03\x05\x02\0\x05\x12\
    \x03\x1c\x04\n\n\x0e\n\x07\x04\0\x03\x05\x02\0\x01\x12\x03\x1c\x0b\x18\n\
    \x0e\n\x07\x04\0\x03\x05\x02\0\x03\x12\x03\x1c\x1b\x1c\n\x0e\n\x06\x04\0\
    \x03\x05\x08\0\x12\x04\x1e\x04\x20\x05\n\x0e\n\x07\x04\0\x03\x05\x08\0\
    \x01\x12\x03\x1e\n\x12\n\r\n\x06\x04\0\x03\x05\x02\x01\x12\x03\x1f\x06\
    \x13\n\x0e\n\x07\x04\0\x03\x05\x02\x01\x05\x12\x03\x1f\x06\x0c\n\x0e\n\
    \x07\x04\0\x03\x05\x02\x01\x01\x12\x03\x1f\r\x0e\n\x0e\n\x07\x04\0\x03\
    \x05\x02\x01\x03\x12\x03\x1f\x11\x12\n\x0e\n\x06\x04\0\x03\x05\x08\x01\
    \x12\x04!\x04#\x05\n\x0e\n\x07\x04\0\x03\x05\x08\x01\x01\x12\x03!\n\x12\
    \n\r\n\x06\x04\0\x03\x05\x02\x02\x12\x03\"\x06\x13\n\x0e\n\x07\x04\0\x03\
    \x05\x02\x02\x05\x12\x03\"\x06\x0c\n\x0e\n\x07\x04\0\x03\x05\x02\x02\x01\
    \x12\x03\"\r\x0e\n\x0e\n\x07\x04\0\x03\x05\x02\x02\x03\x12\x03\"\x11\x12\
    \n\x0e\n\x06\x04\0\x03\x05\x08\x02\x12\x04$\x04&\x05\n\x0e\n\x07\x04\0\
    \x03\x05\x08\x02\x01\x12\x03$\n\x19\n\r\n\x06\x04\0\x03\x05\x02\x03\x12\
    \x03%\x06\x1a\n\x0e\n\x07\x04\0\x03\x05\x02\x03\x05\x12\x03%\x06\x0c\n\
    \x0e\n\x07\x04\0\x03\x05\x02\x03\x01\x12\x03%\r\x15\n\x0e\n\x07\x04\0\
    \x03\x05\x02\x03\x03\x12\x03%\x18\x19\n\x0c\n\x04\x04\0\x08\0\x12\x04+\
    \x021\x03\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03+\x08\x0f\n\x0b\n\x04\x04\0\
    \x02\0\x12\x03,\x04\x1e\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03,\x04\x0e\n\
    \x0c\n\x05\x04\0\x02\0\x01\x12\x03,\x0f\x19\n\x0c\n\x05\x04\0\x02\0\x03\
    \x12\x03,\x1c\x1d\n\x0b\n\x04\x04\0\x02\x01\x12\x03-\x04\x1a\n\x0c\n\x05\
    \x04\0\x02\x01\x06\x12\x03-\x04\x0c\n\x0c\n\x05\x04\0\x02\x01\x01\x12\
    \x03-\r\x15\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03-\x18\x19\n\x0b\n\x04\
    \x04\0\x02\x02\x12\x03.\x04(\n\x0c\n\x05\x04\0\x02\x02\x06\x12\x03.\x04\
    \x13\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03.\x14#\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03.&'\n\x0b\n\x04\x04\0\x02\x03\x12\x03/\x04\x1f\n\x0c\n\
    \x05\x04\0\x02\x03\x06\x12\x03/\x04\x0e\n\x0c\n\x05\x04\0\x02\x03\x01\
    \x12\x03/\x0f\x19\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03/\x1c\x1e\n\x0b\n\
    \x04\x04\0\x02\x04\x12\x030\x04#\n\x0c\n\x05\x04\0\x02\x04\x06\x12\x030\
    \x04\x10\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x030\x11\x1d\n\x0c\n\x05\x04\
    \0\x02\x04\x03\x12\x030\x20\"b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
